before_script: "sudo aptitude -y -q install ffmpeg libvpx-dev libvpx0 x264 libx264-85 libx264-dev"
language: node_js
node_js:
  - "node"
  - "6"
after_success: npm run coverage
# deploy:
#   provider: npm
#   api_key: < travis encrypt YOUR_API_KEY --add deploy.api_key  >
#   skip_cleanup: true
#   on:
#     tags: true