before_install:
  - ./travis-setup.sh
language: node_js
addons:
  apt:
    packages:
    - wget
    - tar
    - bzip2
    - flvtool2
node_js:
  - "node"
  - "6"
after_success: npm run coverage
# deploy:
#   provider: npm
#   api_key: < travis encrypt YOUR_API_KEY --add deploy.api_key  >
#   skip_cleanup: true
#   on:
#     tags: true